package pl.mateusz.recipemanagerbackend.enums;

public enum RecipeTag {
    VEGETARIAN, VEGAN, GLUTEN_FREE, DAIRY_FREE, LOW_CALORIE, KETO,
    LOW_CARB, SWEET, SOUR, SALTY, SPICY, BITTER, BREAKFAST, LUNCH,
    DINNER, DESSERT, SNACK, QUICK, MEDIUM, LONG, PARTY, ROMANTIC, FOR_KIDS, HOLIDAY,
    GRILL, POLISH, ITALIAN, MEXICAN, ASIAN, MEDITERRANEAN, INDIAN, MEAT, FISH,
    VEGETABLES, FRUITS, DAIRY, GRAINS, SPRING, SUMMER, AUTUMN, WINTER, HEALTHY,
    TRADITIONAL, QUICK_MEAL, ONE_POT, TAKEAWAY
}
