-- Sample data generated by gpt

-- Wstawianie poziomów trudności
INSERT INTO difficulty_level (label) VALUES
    ('Łatwy'),
    ('Średni'),
    ('Trudny');

-- Wstawianie tagów
INSERT INTO tag (label) VALUES
    ('Wegetariańskie'),
    ('Bezglutenowe'),
    ('Szybkie'),
    ('Śniadanie'),
    ('Obiad');

-- Wstawianie jednostek miary
INSERT INTO measurement_unit (label) VALUES
    ('g'),
    ('ml'),
    ('sztuka'),
    ('łyżeczka'),
    ('szklanka');

-- Wstawianie użytkowników
INSERT INTO app_user (username, pass) VALUES
    ('jan_kowalski', 'haslo123'),
    ('anna_nowak', 'bezpieczneHaslo'),
    ('marek_wisniewski', 'tajneHaslo');

-- Wstawianie składników
INSERT INTO ingredient (title, unit_id, amount) VALUES
    ('Mąka', 1, 500),
    ('Mleko', 2, 200),
    ('Jajko', 3, 2),
    ('Cukier', 4, 2),
    ('Masło', 1, 50);

-- Wstawianie przepisów
INSERT INTO recipe (title, instructions, preparation_time, author_id, difficulty_id) VALUES
    ('Naleśniki', 'Wymieszaj składniki i usmaż na patelni.', 20, 1, 1),
    ('Ciasto czekoladowe', 'Wymieszaj składniki, piecz przez 30 min.', 40, 2, 2),
    ('Jajecznica', 'Roztrzep jajka i usmaż na patelni.', 10, 3, 1);

-- Wstawianie powiązań przepisów i składników
INSERT INTO recipe_ingredient (recipe_id, ingredient_id) VALUES
    (1, 1), (1, 2), (1, 3), (1, 4),
    (2, 1), (2, 4), (2, 5),
    (3, 3), (3, 5);

-- Wstawianie powiązań przepisów i tagów
INSERT INTO recipe_tag (recipe_id, tag_id) VALUES
    (1, 3), (1, 4),
    (2, 1), (2, 5),
    (3, 4);

-- Wstawianie ocen
INSERT INTO rating (user_id, recipe_id, comment, score) VALUES
    (1, 1, 'Bardzo smaczne!', 9.0),
    (2, 2, 'Trochę za słodkie', 7.0),
    (3, 3, 'Szybkie i proste', 8.0);
