-- Sample data generated by gpt

-- Dodanie poziomów trudności
INSERT INTO difficulty_level (label) VALUES
('Łatwy'),
('Średni'),
('Trudny');

-- Dodanie tagów
INSERT INTO tag (label) VALUES
('Vegetariańskie'),
('Bezglutenowe'),
('Szybkie'),
('Wegetariańskie'),
('Desery');

-- Dodanie jednostek miary
INSERT INTO measurement_unit (label) VALUES
('szt.'),
('kg'),
('g'),
('ml'),
('l');

-- Dodanie składników
INSERT INTO ingredient (title, unit_id, amount) VALUES
('Jabłko', 1, 1.0),
('Mąka', 2, 0.5),
('Cukier', 3, 0.2),
('Masło', 4, 0.1),
('Mleko', 5, 0.5);

-- Dodanie przepisów
INSERT INTO recipe (title, instructions, preparation_time, difficulty_id) VALUES
('Szarlotka', '1. Wymieszaj mąkę, cukier i masło. 2. Wykładaj ciasto na formę. 3. Pokrój jabłka i ułóż na cieście. 4. Piecz przez 40 minut w 180°C.', 60, 1),
('Budyń', '1. Wymieszaj mleko z cukrem i proszkiem budyniowym. 2. Gotuj przez 5 minut. 3. Podawaj na ciepło lub zimno.', 10, 2);

-- Dodanie składników do przepisów
INSERT INTO recipe_ingredient (recipe_id, ingredient_id) VALUES
(1, 1),
(1, 2),
(1, 3),
(2, 4),
(2, 5);

-- Dodanie tagów do przepisów
INSERT INTO recipe_tag (recipe_id, tag_id) VALUES
(1, 1),
(1, 2),
(2, 3);

-- Dodanie użytkowników
INSERT INTO app_user (username, pass) VALUES
('mateusz', 'password123'),
('anna', 'qwerty123'),
('maria', '123456');

-- Dodanie ocen do przepisów
INSERT INTO rating (user_id, recipe_id, comment, score) VALUES
(1, 1, 'Bardzo smaczne, szybkie w przygotowaniu!', 8.5),
(2, 1, 'Świetny przepis, polecam!', 9.0),
(3, 2, 'Prosty i smaczny budyń.', 7.0);
